# 数据操作

1. 张量表示一个数值组成的数组，这个数组可能有多个维度
2. 要改变一个张量的形状，而不改变元素数量和元素值，可以调用``reshape``函数
3. 使用全0、全1、其他常量、或者从特定分布中随机采样的数字
4. 通过提供包含数值的Python列表（或嵌套列表）来为所需张量中的每个元素预付确定值
5. 常见的标准算术运算符（+ - * / 和 **）都可以被升级成为``按元素运算``
    - ** 运算符是求幂运算
6. 把多个张量连结在一起
7. 通过逻辑运算符构建二元张量
8. 对张量中的所有元素进行``求和``，会产生一个只有一个元素的张量
9. 【最容易出错的地方】即使形状不同，任可以通过调用``广播机制(broadcasting mechanism)``来执行按元素操作
10. 可以用``[-1]``选择最后一个元素，可以用``[1:3]``选择第二个和第三个元素

In [2]:
import torch

In [4]:
# 1 张量表示一个数值组成的数组，这个数组可能有多个维度

x = torch.arange(12)
print(x)          # 一维，长度为12
print(x.shape)    # 元素为1的数组
print(x.size())
print(x.numel())

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
torch.Size([12])
torch.Size([12])
12


In [5]:
# 2 要改变一个张量的形状，而不改变元素数量和元素值，可以调用reshape函数

X = x.reshape(3,4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [6]:
# 3 使用全0、全1、其他常量、或者从特定分布中随机采样的数字

torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [7]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [46]:
# 注意
e = torch.arange(12)
f = e.reshape(3,4)
f[:] = 2
e

tensor([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [9]:
# 4 通过提供包含数值的Python列表（或嵌套列表）来为所需张量中的每个元素预付确定值

a = torch.tensor([[2,1,4,3],[1,2,3,4],[4,3,2,1]])    # list of list, 2维
print(a)
print(a.shape) # 2维

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])
torch.Size([3, 4])


In [10]:
b = torch.tensor([[[2,1,4,3],[1,2,3,4],[4,3,2,1]]])    # 3维
print(b)
print(b.shape) # 3维

tensor([[[2, 1, 4, 3],
         [1, 2, 3, 4],
         [4, 3, 2, 1]]])
torch.Size([1, 3, 4])


In [11]:
# 5 常见的标准算术运算符（+ - * / 和 **）都可以被升级成为按元素运算

x = torch.tensor([1.0, 2, 4, 8])    # 1.0: 创建的是浮点元素的数组；1：整数元素数组
y = torch.tensor([2, 2, 2, 2])
x+y, x-y, x*y, x/y, x**y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [12]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [8]:
# 6 把多个张量连结在一起，不改变维度

X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4],[4, 3, 2, 1]])
print(torch.cat((X,Y), dim=0))    # 第0维，按行合并（堆起来）
print(torch.cat((X,Y), dim=1))    # 第1维（最后一维，-1维），按列合并（第2维（3维），dim=2）

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])
tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])


In [7]:
P = torch.arange(12, dtype=torch.float32).reshape((2,2,3))
Q = torch.tensor([[[12, 13, 14],[15, 16, 17]],[[18, 19, 20],[21, 22, 23]]])
print(torch.cat((P,Q), dim=0))    # 第0维，按行合并（堆起来）
print(torch.cat((P,Q), dim=1))    # 第1维，将2个张量的第1维合并
print(torch.cat((P,Q), dim=2))    # 第2维（最后一维，-1），按列合并

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]],

        [[12., 13., 14.],
         [15., 16., 17.]],

        [[18., 19., 20.],
         [21., 22., 23.]]])
tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.],
         [12., 13., 14.],
         [15., 16., 17.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.],
         [18., 19., 20.],
         [21., 22., 23.]]])
tensor([[[ 0.,  1.,  2., 12., 13., 14.],
         [ 3.,  4.,  5., 15., 16., 17.]],

        [[ 6.,  7.,  8., 18., 19., 20.],
         [ 9., 10., 11., 21., 22., 23.]]])


In [17]:
# 7 通过逻辑运算符构建二元张量

X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [10]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [11]:
# 8 对张量中的所有元素进行求和，会产生一个只有一个元素的张量

X.sum()

tensor(66.)

In [20]:
# 9 【最容易出错的地方】即使形状不同，任可以通过调用广播机制(broadcasting mechanism)来执行按元素操作
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [21]:
# 把a复制成3x2矩阵：a = [[0,0],[1,1],[2,2]]
# 把b复制成3x2矩阵：b = [[0,1],[0,1],[0,1]]
# 复制之后，然后相加
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [22]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [27]:
# 10 可以用[-1]选择最后一个元素，可以用[1:3]选择第二个和第三个元素

print(X[-1])    # 取值倒数第一行
print(X[1:3])   # 取值第一行和第二行（开区间）

tensor([ 8.,  9., 10., 11.])
tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


In [12]:
# 11 除读取外，还可以通过指定索引来将元素写入矩阵
X[1, 2] = 9    # 把第一行，第二列的元素改写成【9】
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [13]:
X[0:2, :] = 12    # 把第0行到第1行的所有值，改成【12】
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [16]:
X[0:2] = 11
X

tensor([[11., 11., 11., 11.],
        [11., 11., 11., 11.],
        [ 8.,  9., 10., 11.]])

## 运行一些操作可能会导致为新结果分配内存: 避免重复复制特别大的矩阵，否则导致内存问题

In [17]:

before = id(Y)    # id类似于指针，返回python里唯一的标识号
Y = Y + X
id(Y) == before   # 新的Y的id与旧的Y的id不同

False

## 执行原地操作

In [22]:

Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
# Z = X + Y    # 误用，地址不同   id(Z): 1877546923584    id(Z): 1877546917504
Z[:] = X + Y
print('id(Z):', id(Z))

id(Z): 1877546924800
id(Z): 1877546924800


## 如果在后续计算中没有重复使用X，我们也可以使用*X[:] = X + Y* 或 *X += Y*来减少操作的内存开销

In [23]:
before = id(X)
X += Y
id(X) == before

True

## 转换为numpy张量

In [25]:
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

## 将1维张量转换为Python标量

In [26]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

# 数据预处理

- 读取一个csv文件，做特征处理，成为pytorch能用的tensor

## 创建一个人工数据集，并存储在csv（逗号分割值）文件

In [37]:
import os

os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tiny.csv')

with open(data_file, 'w') as f:
    f.write('NumRooms, Alley, Price\n')    # 列名
    f.write('NaN, Pava, 127500\n')    # 每行表示一个数据样本
    f.write('2, NaN, 106000\n')
    f.write('4, NaN, 178100\n')
    f.write('NaN, NaN, 140000\n')

In [38]:
import pandas as pd

data = pd.read_csv(data_file)
print(data)

   NumRooms  Alley   Price
0       NaN   Pava  127500
1       2.0    NaN  106000
2       4.0    NaN  178100
3       NaN    NaN  140000


## 为了处理缺失的数据，典型的方法包括 插值 和 删除， 这里我们将考虑插值

In [39]:
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]    # 0:2 开区间，第0列：NumRooms，第1列：Alley
inputs = inputs.fillna(inputs.mean(numeric_only=None))
print(inputs)

   NumRooms  Alley
0       3.0   Pava
1       2.0    NaN
2       4.0    NaN
3       3.0    NaN


<ipython-input-39-18c59a149c3c>:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  inputs = inputs.fillna(inputs.mean(numeric_only=None))


### 对于 inputs 中的类别值或离散值，我们将 NaN 视为一个类别

In [44]:
inputs = pd.get_dummies(inputs, dummy_na=True)
print(inputs)

   NumRooms   Alley_ NaN   Alley_ Pava   Alley_nan
0       3.0            0             1           0
1       2.0            1             0           0
2       4.0            1             0           0
3       3.0            1             0           0


## 现在 inputs 和 outputs 中的所有条目都是数值类型，他们可以转换为张量格式

In [42]:
C, d = torch.tensor(inputs.values), torch.tensor(outputs.values)
C, d

(tensor([[3., 0., 1., 0.],
         [2., 1., 0., 0.],
         [4., 1., 0., 0.],
         [3., 1., 0., 0.]], dtype=torch.float64),
 tensor([127500, 106000, 178100, 140000]))