In [1]:
import torch

## 标量由只有一个元素的张量表示

In [2]:
x = torch.tensor([3.0])
y = torch.tensor([2.0])

x+y, x*y, x/y, x**y

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

## 可以将向量视为标量值组成的列表

In [3]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

## 通过张量的索引来访问任一元素

In [4]:
x[3]

tensor(3)

## 访问张量的长度

In [6]:
len(x)

4

## 只有一个轴的张量，形状只有一个元素

In [8]:
x.shape

torch.Size([4])

## 通过指定两个分量 m 和 n 来创建一个形状为 m x n 的矩阵

In [9]:
A = torch.arange(20).reshape(5, 4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

## 矩阵的转置

In [10]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

## 对称矩阵（symmetric matrix） A等于其转置：A = A^T

In [11]:
B = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [12]:
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

## 向量是标量的推广，矩阵是向量的推广，我们可以构建具有更多轴的数据结构

In [14]:
X = torch.arange(24).reshape(2, 3, 4)    # 在1个三维张量中，有2个二维矩阵，每个二维矩阵有3个向量，每个向量有4个标量
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

## 给定具有相同形状的任何两个张量，任何按元素二元运算的结果都将是相同形状的张量

In [15]:
A = torch.arange(20, dtype=torch.float32).reshape(5,4)
B = A.clone()    # 通过分配新内存，将A的一个副本分配给B
A, A+B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

## 两个矩阵 按元素乘法 称为 哈达玛积 （Hadamard product） 数学符号

In [16]:
A * B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [17]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a + X, (a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

## 计算其元素的和

In [23]:
x = torch.arange(4, dtype=torch.float32)
x, x.sum()  # 求和的值，是标量

(tensor([0., 1., 2., 3.]), tensor(6.))

## 表示任意形状张量的元素和

In [19]:
A.shape, A.sum()

(torch.Size([5, 4]), tensor(190.))

In [36]:
A = torch.arange(40, dtype=torch.float32).reshape(2, 5, 4)
A.shape, A.sum()

(torch.Size([2, 5, 4]), tensor(780.))

In [41]:
A

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]],

        [[20., 21., 22., 23.],
         [24., 25., 26., 27.],
         [28., 29., 30., 31.],
         [32., 33., 34., 35.],
         [36., 37., 38., 39.]]])

# 指定求和汇总张量的轴

In [28]:
# 把第一个维度进行求和（2），不管剩下的（5，4）
# 对第一个维度求和：把两个【4 x 5】矩阵相加
A_sum_axis0 = A.sum(axis=0)    
A_sum_axis0, A_sum_axis0.shape

(tensor([[20, 22, 24, 26],
         [28, 30, 32, 34],
         [36, 38, 40, 42],
         [44, 46, 48, 50],
         [52, 54, 56, 58]]),
 torch.Size([5, 4]))

In [29]:
# 把第二个维度进行求和（5），不管剩下的（2，4）
# 对第二个维度求和：把每个【4 x 5】矩阵，按列相加
A_sum_axis1 = A.sum(axis=1)    
A_sum_axis1, A_sum_axis1.shape

(tensor([[ 40,  45,  50,  55],
         [140, 145, 150, 155]]),
 torch.Size([2, 4]))

In [30]:
# 把第一个和第二个维度进行求和（2， 5），不管剩下的（4）
# 对第一个和第二个维度求和：把两个【4 x 5】矩阵，按列相加求总和，维度等于第三维
A_sum_axis01 = A.sum(axis=[0,1])    
A_sum_axis01, A_sum_axis01.shape

(tensor([180, 190, 200, 210]), torch.Size([4]))

### 对于axis的总结：

- axis等于几，相当于把第几维消除。
    - 例如torch.size(2, 5, 4), 
        - 当axis=0，相当于把[5,4]的【5】给消去，剩下的【2, 4】，是一个2行4列的矩阵
        - 当axis=[1,2]，相当于把[5,4]的【5, 4】给消去，剩下的【2】，是一个长为2的向量        
- 把第几维拍扁，其他维度保留？

### 当keepdims = True， axis = 1 时
- 原shape：(2, 5, 4)
- 现shape：(2, 1, 5)

### 当keepdims = True， axis = (1, 2) 时
- 原shape：(2, 5, 4)
- 现shape：(2, 1, 1)

In [86]:
u = torch.arange(24).reshape(2,3,4)
u

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [77]:
# axis = 0
u_sum_axis_0 = u.sum(axis=0)    # 等价于 u[0, :, :] + u[1, :, :]
u_sum_axis_0, u_sum_axis_0.shape

(tensor([[12, 14, 16, 18],
         [20, 22, 24, 26],
         [28, 30, 32, 34]]),
 torch.Size([3, 4]))

In [80]:
u[0, :, :]  + u[1, :, :]

tensor([[12, 14, 16, 18],
        [20, 22, 24, 26],
        [28, 30, 32, 34]])

In [84]:
# axis = 1
u_sum_axis_1 = u.sum(axis=1)
u_sum_axis_1, u_sum_axis_1.shape

(tensor([[12, 15, 18, 21],
         [48, 51, 54, 57]]),
 torch.Size([2, 4]))

In [82]:
# axis = 2
u_sum_axis_2 = u.sum(axis=2)
u_sum_axis_2, u_sum_axis_2.shape

(tensor([[ 6, 22, 38],
         [54, 70, 86]]),
 torch.Size([2, 3]))

## 平均值（mean或average）

In [37]:
A.mean()

tensor(19.5000)

In [38]:
A.sum()/A.numel()

tensor(19.5000)

## 计算总和或均值时保持轴数不变

In [56]:
A = torch.arange(20, dtype=torch.float32).reshape(5,4)
sum_A = A.sum(axis=1, keepdims=True)
A, sum_A

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 6.],
         [22.],
         [38.],
         [54.],
         [70.]]))

## 通过广播，将A 除以 sum_A

In [45]:
A / sum_A

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

## 某个轴 计算A元素的积累总和

In [47]:
A.cumsum(axis=0)

tensor([[ 0,  1,  2,  3],
        [ 4,  6,  8, 10],
        [12, 15, 18, 21],
        [24, 28, 32, 36],
        [40, 45, 50, 55]])

## 点积是相同位置的按元素乘积的和

In [50]:
y = torch.ones(4, dtype=torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

# 矩阵乘法

## 通过执行按元素乘法，然后进行求和来表示两个向量的点积

In [51]:
torch.sum(x * y)

tensor(6.)

## 矩阵向量积 Ax 是一个长度为m的列向量，其第i个元素是是点积a_i^T * x_i

In [59]:
A, x

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([0., 1., 2., 3.]))

In [58]:
A.shape, x.shape, torch.mv(A, x)  # 矩阵向量的乘积，matrix vector multiplication

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

In [60]:
## 我们可以将矩阵-矩阵乘法AB看作是简单地执行m次矩阵 - 向量积，并将结果拼接在一起，形成一个n x m 矩阵

In [61]:
B = torch.ones(4, 3)
torch.mm(A, B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

# 范数：向量或矩阵的长度

## L2 范数是向量元素的平方和的平方根：

<img src="./pic/L2范数.PNG" width=200  heigth=200>


## L1 范数是向量元素的绝对值之和：

<img src="./pic/L1范数.PNG" width=200  heigth=200>

## 矩阵的 弗罗贝尼乌斯范数（Forbenius norm）是矩阵元素的平方和的平方根
- 等价于把矩阵拉成一个向量，然后再求向量的范数

<img src="./pic/F范数.PNG"  width=200  heigth=200>

## L2范数是针对向量而言的，F范数是针对矩阵而言的

In [ ]:
# <img src="./pic/L2范数.PNG" style="float: left;" width=200  heigth=200>

In [64]:
# L2 范数
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

In [65]:
# L1 范数
torch.abs(u).sum()

tensor(7.)

In [71]:
# F范数
torch.norm(torch.ones((4,9)))

tensor(6.)

### Q: 赋值语句为什么要多加一个括号？
### A: 加括号相当于使用元组创建三维的tensor。也可以把里面的变为中括号，那就是使用列表创建三维tensor。二者同理

In [72]:
torch.ones(4,9), torch.ones((4,9))

(tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1.]]),
 tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1.]]))

In [94]:
g = torch.ones((2, 5, 4))
g, g.shape, g.sum(), g.sum().shape

(tensor([[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],
 
         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]]),
 torch.Size([2, 5, 4]),
 tensor(40.),
 torch.Size([]))

In [96]:
g.sum(axis=0), g.sum(axis=0).shape

(tensor([[2., 2., 2., 2.],
         [2., 2., 2., 2.],
         [2., 2., 2., 2.],
         [2., 2., 2., 2.],
         [2., 2., 2., 2.]]),
 torch.Size([5, 4]))

In [98]:
g.sum(axis=0, keepdims=True).shape

torch.Size([1, 5, 4])

In [93]:
g.sum(axis=1), g.sum(axis=1).shape

(tensor([[5., 5., 5., 5.],
         [5., 5., 5., 5.]]),
 torch.Size([2, 4]))

In [97]:
g.sum(axis=2), g.sum(axis=2).shape

(tensor([[4., 4., 4., 4., 4.],
         [4., 4., 4., 4., 4.]]),
 torch.Size([2, 5]))

In [99]:
g.sum(axis=[0, 2], keepdims=True).shape

torch.Size([1, 5, 1])

In [ ]:
# Q: torch不区分行向量和列向量吗？
### A：一维向量是行向量（长度为n），列向量一定是一个矩阵（行数为n，列数为1）